name: Backend CI - Test, Build & Push Images
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'
 
jobs:
  # Job 1: Test & Lint
  test_and_lint_backends:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      # Example: Python backend testing
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
 
      - name: Install dependencies
        run: |
          cd backend/product_service
          pip install -r requirements.txt || true
          cd ../order_service
          pip install -r requirements.txt || true
 
      - name: Run flake8 lint
        run: |
          pip install flake8 || true
          flake8 backend || true
 
      - name: Run pytest
        run: |
          pip install pytest || true
          pytest backend || true
 
  # Job 2: Build & Push (depends on tests)
  build_and_push_backend:
    runs-on: ubuntu-latest
    needs: test_and_lint_backends   # only runs if tests pass
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      # Azure login (uses service principal JSON)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
 
      # Login to Azure Container Registry (ACR) using SHORT registry name (e.g., sit722week07acr)
      - name: Login to ACR
        run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}
 
      # Build & push product_service
      - name: Build and Push product_service
        run: |
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/product_service:latest ./backend/product_service
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/product_service:latest
 
      # Build & push order_service
      - name: Build and Push order_service
        run: |
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/order_service:latest ./backend/order_service
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/order_service:latest
 
      # Logout
      - name: Logout from Azure
        if: always()
        run: az logout
